Make project compatible with recent python versions
haddocking/haddock3 pull request #1042
Opened 2024-09-23 14:06 UTC by rvhonorato

You are about to submit a new Pull Request. Before continuing make sure you read the [contributing guidelines](CONTRIBUTING.md).

## Checklist

- [ ] Tests added for the new code
- [ ] Documentation added for the code changes
- [ ] Does not break licensing
- [ ] Does not add any dependencies, if it does please add a thorough explanation

## Summary of the Pull Request  

## Related Issue

## Additional Info

2024-09-23 14:08 UTC, rvhonorato commented on src/haddock/libs/libalign.py
> +        if not np.any(self.top_alns[align_id].aligned):
This here was causing 

```
The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

Yes it took me hours to find it 🫠

2024-09-25 14:40 UTC, mgiulini requested changes
Looks good but the sphinx commands cannot build the developer documentation (see below)

2024-09-27 13:23 UTC, rvhonorato commented on .github/workflows/ci.yml
> +          sphinx-build docs haddock3-docs
Yep, i said this in the PR description:

> The doc build part is very weirdly implemented and it broke with this PR, I will fix it in another.

2024-09-27 14:42 UTC, mgiulini submitted a review, later dismissed

2024-09-27 14:42 UTC, mgiulini commented on tests/test_module_rmsdmatrix.py
> +    """???"""
```suggestion
    """rmsdmatrix module fixture"""
```

2024-09-27 14:42 UTC, mgiulini commented on tests/test_module_rmsdmatrix.py
> +    # rmsd_module.previous_io.output = protdna_input_list
```suggestion
        )
```

2024-09-27 14:42 UTC, mgiulini commented on tests/test_module_topoaa.py
> +    """???"""
```suggestion
    """topoaa module fixture"""
```

2024-09-27 14:42 UTC, mgiulini commented on tests/test_module_mdscoring.py
> +    """???"""
```suggestion
    """mdscoring module fixture"""
```

2024-09-27 14:42 UTC, mgiulini commented on tests/test_module_mdscoring.py
> +    """???"""
```suggestion
    """mdscoring module fixture protdna"""
```

2024-09-27 14:42 UTC, mgiulini commented on tests/test_module_seletopclusts.py
> +    # assert sorted_models[1].file_name == "protprot_complex_1.pdb"
can we remove this? or do you want to keep the commented lines for future reference?

2024-09-27 14:58 UTC, mgiulini approved these changes

2024-09-30 18:42 UTC, amjjbonvin approved these changes
Nice!

Out of curiosity: where are the tests actually running when the path is defined as path=Path(".") ? Under some /var/tmp directory?

2024-09-30 18:42 UTC, merged