Fix z restraints examples
haddocking/haddock3 pull request #1101
Opened 2024-10-15 10:21 UTC by VGPReys

## Summary of the Pull Request  

Fixing the examples in `examples/docking-protein-surface` to be functional with current implementation.

## Related Issue

Closes #1100 

## Additional Info

Kept future implementation in `.__future__.docking-protein-surface`, to minimize later efforts.

2024-10-15 13:52 UTC, rvhonorato requested changes
"Fixing the examples in examples/docking-protein-surface to be functional with current implementation." is not very clear - could you please update it with what is the issue?

2024-10-16 07:23 UTC, VGPReys commented
The issue is that the z-restraints PR (#839) has been modified to be functional with the [`haddock-restraints`](https://github.com/haddocking/haddock-restraints), that is not yet implemented.
So the idea is to make the current examples functional with the current implementation in `haddock3`.
I allowed myself to keep the `haddock-restraints` "implementation in .__future__.docking-protein-surface, to minimize later efforts" when `haddock-restraints` will be installed together with `haddock3`.
I hope this clarifies the purpose of this PR.

2024-10-16 08:12 UTC, rvhonorato commented
Please add this description in the PR description. We use GitHub for some reasons, one of them is that we can keep track of what happened in the code.

2024-10-16 09:33 UTC, rvhonorato approved these changes

2024-10-16 09:42 UTC, merged