Implement `caprieval`
haddocking/haddock3 pull request #122
Opened 2021-11-15 16:42 UTC by rvhonorato

This PR is a work-in-progress, I will let it as a draft here so we can discuss things.

🚧 🚧 🚧 🚧 🚧 🚧

2021-11-18 12:12 UTC, joaomcteixeira reviewed
just comments

2021-11-18 12:12 UTC, joaomcteixeira commented on .gitmodules
> +	ignore = dirty
once `fccpy` gets developed this should become a dependency and not a submodule.

2021-11-18 12:12 UTC, joaomcteixeira commented on requirements.yml
> +    - python==3.9
i am working with @JoaoRodrigues to understand what in FCCpy is incompatible with python 3.8. If there is no special reason we should keep it `3.8` compatible.

2021-11-18 12:12 UTC, joaomcteixeira commented on requirements.yml
> +        - git+https://github.com/joaorodrigues/fcc@fcc2
This is okay, so we don't need to submodule anymore.

2021-11-18 12:12 UTC, joaomcteixeira commented on src/haddock/modules/analysis/caprieval/__init__.py
> +        exec_path = Path(bin_path, dcfg['contact_exec'])
We should make that `contact_exec` some module.

2021-11-22 14:52 UTC, rvhonorato commented
This is finalized, still failing because of py38 issues, @joaomcteixeira up to you to either bump or refactor the dependency

2021-11-22 16:08 UTC, joaomcteixeira commented
You can merge, bump it to python 3.9. Don't worry about the tests I will correct it in another PR. Don't squash merge next time :wink:

2021-11-22 16:09 UTC, joaomcteixeira commented
But, have you worked out the new fccpy dependency? that fccpy works only in a branch of @JoaoRodrigues . Not so safe for now, though

2021-11-22 16:18 UTC, joaomcteixeira requested changes

2021-11-22 16:18 UTC, joaomcteixeira commented on src/haddock/modules/analysis/caprieval/__init__.py
> +    def confirm_installation(cls):
This must be filled

2021-11-22 16:19 UTC, joaomcteixeira commented on src/haddock/modules/analysis/caprieval/__init__.py
> +    def confirm_installation(cls):
Sorry, no need because it is a dependency.

2021-11-22 16:56 UTC, joaomcteixeira commented on tox.ini
> -[testenv:py38]
This block needs to exist. change to `[testenv:py39]`

2021-11-22 16:56 UTC, joaomcteixeira commented on tox.ini
>  [testenv:py39]
this block you can remove.

2021-11-22 20:56 UTC, closed without merging