Cleaned emref module and adapted other to new env variables
haddocking/haddock3 pull request #140
Opened 2021-11-23 20:09 UTC by amjjbonvin

Docking example now works including the emref module.
Adapted all previous modules to use the new environment variables (related to issue 
Next step is mdref

PS: The environment variables are printed in the output for each model - must be an old debug statement remaining somewhere in the python code

2021-11-23 20:25 UTC, rvhonorato reviewed
194 files, impossible to check everything, will trust @amjjbonvin also on this one!

2021-11-23 21:28 UTC, joaomcteixeira commented on src/haddock/modules/refinement/emref/__init__.py
> +                ambig=self.params.get('ambig', None),
This was a good bug!

2021-11-23 21:44 UTC, joaomcteixeira commented
> PS: The environment variables are printed in the output for each model - must be an old debug statement remaining somewhere in the python code

taking note of this

2021-11-23 23:29 UTC, joaomcteixeira commented
I agree with Rodrigo. Got ahead and merge this PR on your own :rocket: :guitar: :fire:

2021-11-24 08:26 UTC, joaomcteixeira requested changes
Give me some time to clear some small bugs relating to var names.

2021-11-24 08:26 UTC, joaomcteixeira commented on src/haddock/modules/refinement/emref/__init__.py
> +                ambig=self.params.get('ambig', None),
There is a bug here with `ambig` not being `ambig_fname`. I will correct that and inspect also other things. Please wait before merging.

2021-11-24 09:00 UTC, joaomcteixeira commented
The `ambig_fname` was not being loaded due to an error in the variable name being pulled from the param dictionary `ambig` instead of `ambig_fname`. I am correcting that and working on a way to block future var typing errors at this stage. Var typing errors are already corrected when writing the config.

2021-11-24 09:21 UTC, joaomcteixeira commented
@amjjbonvin I corrected the capturing of `ambig_fname` parameter. Before there was an error and the ambig file was **NOT** being loaded into the CNS `.inp` file because `self.params.get('ambig', None)` was being used and masked the bug. Now that `ambig_fname = ""` is part of the `defaults.cfg` this can be rewritten to a normal `self.params['ambig_fname']`.


You may wish to review the calculations again after [this change](https://github.com/haddocking/haddock3/pull/140/commits/0b7678445cf520311a261fea95faa035e1abeb80).

2021-11-24 11:45 UTC, amjjbonvin commented
Ok- thanks - is this part of the PR I should merge?

Did you check the other modules, they all seem to use the same construction, i.e. ambig and not ambig_fname…

And it was working.

2021-11-24 11:53 UTC, joaomcteixeira commented
Yes, I checked the other modules. All corrected now. The new changes are already part of the of this branch. When the PR it merged the new changes will go along. I was working on #138 from this branch. If you want we can solve that before merging this one. Would be best I think.

2021-11-24 11:56 UTC, amjjbonvin commented
Ok - then try to solve it - I won’t update further the modules until this is solved.

2021-11-24 12:12 UTC, joaomcteixeira commented
Perfect. Converted to `draft` until #142 is solved.

2021-11-24 16:28 UTC, joaomcteixeira commented
Because we closed #142, I think this is safe to merge. Whatever comes after #142 is big enough to hold by itself.

2021-11-24 16:29 UTC, joaomcteixeira approved these changes

2021-11-24 16:30 UTC, merged