Compress `.inp`, `.out`, and `.seed` in CNS Jobs on the fly
haddocking/haddock3 pull request #594
Opened 2022-12-01 16:36 UTC by joaomcteixeira

You are about to submit a new Pull Request. Before continuing make sure you read the [contributing guidelines](CONTRIBUTING.md) and you comply with the following criteria:

- [ ] You have stick to Python. Talk with us before adding other programming languages to HADDOCK3
- [ ] Your PR is about CNS
- [ ] Your code is well documented: proper docstrings and explanatory comments for those tricky parts
- [ ] You structured the code into small functions as much as possible. You can use classes if there's a (state) purpose
- [ ] code follows our coding style
- [ ] You wrote tests for the new code
- [ ] `tox` tests pass. *Run `tox` command inside the repository folder*
- [ ] `-test.cfg` examples execute without errors. *Inside `examples/` run `python run_tests.py -b`*
- [ ] PR does not add any *install dependencies* unless permission granted by the HADDOCK team
- [ ] PR does not break licensing
- [ ] Your PR is about writing documentation for already existing code :fire:
- [ ] Your PR is about writing tests for already existing code :godmode:

---

Partially addresses #587.
@amjjbonvin can you test this? In case you don't yet have my fork on your clone:

```
git remote add joaot https://github.com/joaomcteixeira/haddock3
git fetch joaot
git checkout unpackmore
```

And test some example.  Let me know if you with more to be done regarding **on the fly packing of output files**.

Cheers!

2022-12-02 08:40 UTC, amjjbonvin requested changes
No need to compress on the fly the `.inp` and `.seed` files - those a peanuts in terms of size. 
Best to only archive those with the clean command.

The `.out` files are on contrary very large and compressing them will save a lot of space.

2022-12-02 09:17 UTC, joaomcteixeira commented
It also takes peanuts to compress those. I can make that an internal option so that each module can operate as desired.

2022-12-02 09:20 UTC, amjjbonvin commented
> It also takes peanuts to compress those. I can make that an internal option so that each module can operate as desired.

But it is not worth it... Ok to archive those all into one gzipped archive. Not worth compressing them individually.

2022-12-02 09:24 UTC, joaomcteixeira commented
Okay. Done. Now it's an option with default to `False`. **Only** compresses `.out` files. But I need to see now how the `clean` option would work. Let's make that another PR?

2022-12-02 10:01 UTC, amjjbonvin commented
I guess the clean option should archive any `.out` and `.out.gz` files

2022-12-02 11:14 UTC, mgiulini commented
Nice work! I tested it on the protein-protein-docking-test scenario and the folder size dropped from 30M to 18M.
I would set the `compress_inp` and `compress_seed` options to `True` by default, thus compressing inp and seed files into two archives by default. I think this can be useful for a better readability and faster listing of the important files (thinking about high sampling).

2022-12-02 11:19 UTC, amjjbonvin commented
> I would set the compress_inp and compress_seed options to True by default, thus compressing inp and seed files into two archives by default.
> 
The seed files are needed by the next step, i.e. not a good idea.

ing files could be archived by default, but it does not make sense to gzip each individual file for those.

The out files are a different issue. It is best to gzip those on the fly for each completed model.
And at the end if clean is true archive them into one archive

2022-12-02 11:31 UTC, mgiulini commented
> I would set the compress_inp and compress_seed options to True by default, thus compressing inp and seed files into two archives by default.
> The seed files are needed by the next step, i.e. not a good idea. ing files could be archived by default, but it does not make sense to gzip each individual file for those. The out files are a different issue. It is best to gzip those on the fly for each completed model. And at the end if clean is true archive them into one archive

makes sense!

2022-12-02 12:36 UTC, joaomcteixeira commented
Okay, will do

2022-12-03 10:57 UTC, joaomcteixeira commented
Okay. I am in the making of it. Need to review some of the tests and some parts.

2022-12-03 15:56 UTC, joaomcteixeira commented
Hi.

Implemented all requirements in #587 and #593. Finishing some tests on the `*-test.cfg`. I will let you know when they are done. :+1:

2022-12-03 18:55 UTC, amjjbonvin approved these changes

2022-12-03 18:57 UTC, amjjbonvin commented
Just to confirm: are the out files gzipped first on the fly for each completed model? Or is the cleaning only occurring at the end of a module / run?

To save space while running, compression on the fly of the out files is a must (actually irrespective of the clean options)

2022-12-03 20:02 UTC, joaomcteixeira commented
> Just to confirm: are the out files gzipped first on the fly for each completed model? 

Yes. Always.

Plus, the `clean`, if `True`, will further compress the other files and delete all but the first for `inp` and `out`. I updated the docs also.

But I am having  some error in the `test` I will try to sort it out soon. Don't merge yet.

2022-12-04 09:06 UTC, joaomcteixeira commented
The tests ended, and I tried also the `--restart` and `haddock3-copy` commands, and were working. I think it's safe to merge. You can test it further locally. Let me know.
Cheers!

2022-12-04 09:07 UTC, joaomcteixeira commented on src/haddock/libs/libworkflow.py
> +        self._terminated = None
Note for the future. This was one of the most tricky parts of this implementation.

2022-12-04 09:31 UTC, amjjbonvin approved these changes

2022-12-04 10:39 UTC, merged