better description for some modules
haddocking/haddock3 pull request #947
Opened 2024-07-18 13:42 UTC by VGPReys

You are about to submit a new Pull Request. Before continuing make sure you read the [contributing guidelines](CONTRIBUTING.md) and that you comply with the following criteria:

- [ ] You have sticked to Python. Please talk to us before adding other programming languages to HADDOCK3
- [ ] Your PR is about CNS
- [ ] Your code is well documented: proper docstrings and explanatory comments for those tricky parts
- [ ] You structured the code into small functions as much as possible. You can use classes if there is a (state) purpose
- [ ] Your code follows our coding style
- [ ] You wrote tests for the new code
- [ ] `tox` tests pass. *Run `tox` command inside the repository folder*
- [ ] `-test.cfg` examples execute without errors. *Inside `examples/` run `python run_tests.py -b`*
- [ ] PR does not add any dependencies, unless permission granted by the HADDOCK team
- [ ] PR does not break licensing
- [X] Your PR is about writing documentation for already existing code :fire:
- [ ] Your PR is about writing tests for already existing code :godmode:

---

Closes #944

2024-07-18 14:00 UTC, mgiulini approved these changes

2024-07-18 14:00 UTC, mgiulini commented on src/haddock/modules/topology/topoaa/__init__.py
> +(appart from standard amino-acids, some modified ones, DNA, RNA, ions
```suggestion
(apart from standard amino-acids, some modified ones, DNA, RNA, ions
```

2024-07-19 07:07 UTC, mgiulini submitted a review, later dismissed

2024-07-19 07:07 UTC, mgiulini commented on src/haddock/modules/analysis/contactmap/__init__.py
> +connecting with *chords* the two resiudes that are contacting.
```suggestion
connecting with *chords* the two residues that are contacting.
```

2024-07-19 07:07 UTC, mgiulini commented on src/haddock/modules/refinement/emref/__init__.py
> +the conjugate gradient method develped by
```suggestion
the conjugate gradient method developed by
```

2024-07-23 13:08 UTC, rvhonorato approved these changes

2024-07-23 13:26 UTC, amjjbonvin commented on src/haddock/modules/refinement/flexref/__init__.py
> +is a semi-flexible simulated annealing (SA) protocol in torsion angle space.
protocol based on molecular dynamics in torsion angle space

2024-07-23 13:26 UTC, amjjbonvin commented on src/haddock/modules/refinement/flexref/__init__.py
> +
By default, only the interface regions is treated as flexible. It is automatically defined based on the intermolecular contacts made. It is also possible to manually define the semi-flexible regions, and also define fully flexible regions that are allowed to move throughout the entire protocol from the high temperature rigid body molecular dynamics on.

2024-07-23 13:26 UTC, amjjbonvin commented on src/haddock/modules/refinement/flexref/__init__.py
> +- High temperature rigid body search
Replace "search" by "molecular dynamics"

2024-07-23 13:26 UTC, amjjbonvin commented on src/haddock/modules/refinement/mdref/__init__.py
> +- 3 stages of water heating to reach 300K (at 100, 200 and 300K)
water heating by molecular dynamics

2024-07-23 13:26 UTC, amjjbonvin commented on src/haddock/modules/refinement/mdref/__init__.py
> +- A series of steps at 300K.
Molecular dynamics at 300K

2024-07-23 13:26 UTC, amjjbonvin commented on src/haddock/modules/refinement/mdref/__init__.py
> +- 3 stages of water cooling, to reach 100K (at 300, 200 and 100K)
water cooling by molecular dynamics

2024-07-23 13:26 UTC, amjjbonvin commented on src/haddock/modules/topology/topoaa/__init__.py
> +- Obtain MD parameters
Remove: Obtain MD parameters

2024-07-23 13:26 UTC, amjjbonvin commented on src/haddock/modules/topology/topoaa/__init__.py
> +- Build the topology
Build and write out topologies (psf) and coordinates (pdb) files

2024-07-23 13:26 UTC, amjjbonvin commented on src/haddock/modules/topology/topoaa/__init__.py
> +of MD related tasks.
EM/MD

2024-07-23 13:26 UTC, amjjbonvin commented on src/haddock/modules/topology/topoaa/__init__.py
> +Indeed, having access to parameters and topology is mandatory for any kind
Remove: Indeed,

2024-07-23 13:26 UTC, amjjbonvin commented on src/haddock/modules/topology/topoaa/__init__.py
> +such as small-molecules, parameters and topology must be obtained and provided,
provided by the user

2024-07-24 06:43 UTC, rvhonorato commented on src/haddock/modules/topology/topoaa/__init__.py
> +(https://rascar.science.uu.nl/haddock2.4/library)),
```suggestion
(https://wenmr.science.uu.nl/haddock2.4/library)),
```

2024-07-24 06:47 UTC, amjjbonvin approved these changes
Do implement Rodrigo's suggestion for the URL

2024-07-24 08:11 UTC, rvhonorato requested changes
Building the docs to check the changes, it seems that this esoteric documentation building pipeline renders the docstrings as `rst` and then `html`, but your changes are in markdown.

So they are not rendered properly:

![Schermafbeelding 2024-07-24 100302](https://github.com/user-attachments/assets/5312fd40-d02b-4064-83d0-0b9e11e79a7b)

Have a look here for the proper syntax: https://www.sphinx-doc.org/en/master/usage/restructuredtext/index.html

2024-07-24 08:11 UTC, rvhonorato commented on src/haddock/modules/refinement/emref/__init__.py
> +[Powell](https://en.wikipedia.org/wiki/Powell%27s_method),
The syntax for links is 
```rst
`Powell <https://en.wikipedia.org/wiki/Powell%27s_method>`_
```

2024-07-24 08:11 UTC, rvhonorato commented on src/haddock/modules/refinement/emref/__init__.py
> +The `[emref]` module refine the input complexes by energy minimization using
The syntax for code block is 

```rst
``[emref]``
```

2024-07-24 08:24 UTC, amjjbonvin commented
The current syntax is a proper markdown syntax, but I guess we are speaking here about python code/comments, correct?

> On 24 Jul 2024, at 10:11, Rodrigo Vargas Honorato ***@***.***> wrote:
> 
> +[Powell](https://en.wikipedia.org/wiki/Powell%27s_method),
> The syntax for links is
> 
> `Powell <https://en.wikipedia.org/wiki/Powell%27s_method>`_
>

2024-07-24 14:00 UTC, rvhonorato commented
> The current syntax is a proper markdown syntax, but I guess we are speaking here about python code/comments, correct?


?

2024-07-24 14:02 UTC, amjjbonvin commented
I mean:

> [Powell](https://en.wikipedia.org/wiki/Powell%27s_method)

is a correct markdown syntax for a link.

2024-07-24 15:46 UTC, rvhonorato commented
It is, yes - however the changes in this PR should be in RST

2024-07-25 11:39 UTC, amjjbonvin commented on src/haddock/modules/refinement/emref/__init__.py
> +`Powell <https://en.wikipedia.org/wiki/Powell%27s_method>`_,
Seems random to add a link to Powel and not other things. I would  remove it and simply write: "by conjugate gradient energy minimisation."

2024-07-29 15:37 UTC, amjjbonvin approved these changes

2024-07-29 15:45 UTC, mgiulini approved these changes

2024-07-30 06:52 UTC, merged